# Generated by Django 3.2.13 on 2022-06-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "Profile"},
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="crypto_wallet",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
