# Generated by Django 3.2.13 on 2022-06-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20220623_0500"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A-", "Amin"),
                    ("A+", "Apos"),
                    ("O-", "Omin"),
                    ("O+", "Opos"),
                    ("B-", "Bmin"),
                    ("B+", "Bpos"),
                    ("AB-", "Abmin"),
                    ("AB+", "Abpos"),
                ],
                max_length=3,
            ),
        ),
    ]
