# Generated by Django 3.2.14 on 2022-07-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="crypto_wallet",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
