# Generated by Django 3.2.13 on 2022-07-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0004_request_file_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="details",
            field=models.TextField(blank=True, default=""),
        ),
    ]
