# Generated by Django 3.2.14 on 2022-07-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0005_alter_request_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Ongoing"), (2, "Complete"), (3, "Canceled")],
                null=True,
            ),
        ),
    ]
