# Generated by Django 3.2.14 on 2022-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0006_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
