# Generated by Django 3.2.13 on 2022-06-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requests_api", "0002_auto_20220626_1933"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="modifiedAt",
            new_name="modified_at",
        ),
    ]
