# Generated by Django 3.2.13 on 2022-06-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0001_initial"),
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="requests.request",
            ),
        ),
    ]
