# Generated by Django 3.2.13 on 2022-06-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="createdAt",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="donor",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="modifiedAt",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="request",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="status",
        ),
    ]
