# Generated by Django 3.2.13 on 2022-07-08 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0003_auto_20220629_0901"),
        ("users", "0005_alter_userprofile_blood_type"),
        ("donations", "0002_auto_20220629_0759"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="requests.request",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Complete"), (3, "Canceled")],
                null=True,
            ),
        ),
    ]
