# Generated by Django 3.2.14 on 2022-07-19 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userprofile_user"),
        ("donations", "0003_auto_20220708_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to="users.userprofile",
            ),
        ),
    ]
