# Generated by Django 3.2.14 on 2022-07-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_auto_20220719_1313"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
