# Generated by Django 3.2.14 on 2022-07-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_auto_20220719_1313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Pending"), (2, "Complete"), (3, "Canceled")],
                default=1,
                null=True,
            ),
        ),
    ]
