# Generated by Django 3.2.14 on 2022-07-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0005_alter_donation_status"),
        ("donations", "0005_donation_image"),
    ]
