# Generated by Django 3.2.14 on 2022-07-24 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0006_alter_userprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Attributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "attr_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nft.attributename",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NFTMint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.CharField(max_length=255)),
                ("signed_message", models.CharField(max_length=255)),
                ("signature_v", models.IntegerField()),
                ("signature_r", models.CharField(max_length=255)),
                ("signature_s", models.CharField(max_length=255)),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nft_mint",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NFT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                (
                    "attributes",
                    models.ManyToManyField(
                        related_name="nft", to="nft.Attributes"
                    ),
                ),
            ],
        ),
    ]
