# Generated by Django 3.2.14 on 2022-08-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nft", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributes",
            options={"verbose_name_plural": "Attributes"},
        ),
    ]
