# Generated by Django 3.2.14 on 2022-08-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nft", "0002_alter_attributes_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attributes",
            name="attr_name",
        ),
        migrations.AddField(
            model_name="attributes",
            name="name",
            field=models.CharField(default="default name", max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AttributeName",
        ),
    ]
