# Generated by Django 3.2.13 on 2022-06-29 21:30

from typing import Any

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A-", "Amin"),
                            ("A+", "Apos"),
                            ("O-", "Omin"),
                            ("O+", "Opos"),
                            ("B-", "Bmin"),
                            ("B+", "Bpos"),
                            ("AB-", "Abmin"),
                            ("AB+", "Abpos"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=6,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("details", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
