# Generated by Django 3.2.13 on 2022-06-12 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A-", "A-"),
                            ("A+", "A+"),
                            ("B-", "B-"),
                            ("B+", "B+"),
                            ("O-", "O-"),
                            ("O+", "O+"),
                            ("AB-", "AB-"),
                            ("AB+", "AB+"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                        ],
                        max_length=6,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("details", models.TextField()),
                (
                    "donors",
                    models.ManyToManyField(
                        related_name="request_donor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
