# Generated by Django 3.2.13 on 2022-06-19 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("modifiedAt", models.DateTimeField(auto_now=True)),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A-", "Amin"),
                            ("A+", "Apos"),
                            ("O-", "Omin"),
                            ("O+", "Opos"),
                            ("B-", "Bmin"),
                            ("B+", "Bpos"),
                            ("AB-", "Abmin"),
                            ("AB+", "Abpos"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=6,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("details", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_requests",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
