# Generated by Django 3.2.13 on 2022-06-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='blood_type',
            new_name='bloodType',
        ),
    ]
