# Generated by Django 3.2.13 on 2022-06-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0002_rename_blood_type_request_bloodtype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="created_at",
            new_name="createdAt",
        ),
        migrations.RenameField(
            model_name="request",
            old_name="modified_at",
            new_name="modifiedAt",
        ),
    ]
