name: CI/CD Workflow

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(?:Merge(?:.|\n)+)|(?:[A-Z][a-z].{2,70}|[a-z]{4,8}:\s.{2,64}(?:\n\n[A-Z][a-z](?:\n|.)+)?)$'
          flags: ""
          error: "Write proper git commit messages."
          excludeDescription: "true"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Line Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "^.{4,72}$"
          flags: "gm"
          error: "The maximum line length of 72 characters is exceeded."
          excludeDescription: "true"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Access Repository
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.13

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: poetry-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: cache-v1-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies with poetry
        if: steps.poetry-deps.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Lint with isort
        run: poetry run isort --check-only .

      - name: Lint with black
        run: poetry run black --check .

      - name: Lint with mypy
        run: poetry run mypy .

      - name: Lint with pylint
        run: poetry run pylint **/*.py

      - name: Test with pytest
        run: poetry run pytest --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Access repository
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "masterclass-blood-chain"
          heroku_email: "malthunayan4@gmail.com"

      - name: Run migrations on Heroku
        run: heroku run python manage.py migrate
